# Generated by Django 5.0.6 on 2024-05-15 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_reply_replied_to_alter_reply_parent_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='dislikes',
            field=models.ManyToManyField(related_name='reply_dislikes', to=settings.AUTH_USER_MODEL, verbose_name='Дизлайк'),
        ),
        migrations.AddField(
            model_name='reply',
            name='likes',
            field=models.ManyToManyField(related_name='reply_likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайк'),
        ),
    ]
