# Generated by Django 5.0.6 on 2024-05-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_caruselitems_alter_review_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caruselitems',
            name='description',
            field=models.TextField(max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='caruselitems',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
    ]
