# Generated by Django 5.0.6 on 2024-05-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_caruselitems_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/gallery', verbose_name='Галлерея')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=200, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Галлерея',
                'verbose_name_plural': 'Галлерея',
            },
        ),
        migrations.AlterModelOptions(
            name='caruselitems',
            options={'verbose_name': 'Карусель', 'verbose_name_plural': 'Карусель'},
        ),
    ]
